server:
  port: "9096"
  mode: "debug" # debug, release

proxy:
  url: "http://127.0.0.1:8096"
  api_key: "your_emby_api_key_here"
  cache_time: 1 # 缓存直链时间，单位：小时
  cache_pickcode: true # 缓存 pickcode 到 sqlite 数据库，提高服务速度
  add_metadata: true # 补充元数据
  # 302 方式说明
  # 1. alist: 通过路径映射替换，直接请求 alist 的直链
  # 2. ck 会降级到 115open 方案，再降级到 alist 方案
  # 3. ck+115open: 通过Cookie快速获取文件PickCode，然后请求115open的直链
  method: "alist" # alist, ck, ck+115open
  # 路径映射，用于将 Emby 的原始路径映射到代理的实际路径
  # real 字符串替换后为真实的网盘路径（用于 ck+115open 方案）
  paths:
    - old: "/vol1/1000/CloudNAS/CloudDrive/115"
      new: "/115"
      real: ""

# 使用 ck 或 ck+115open 方案时，需要配置115 Cookie
driver115:
  cookie: "UID=your_uid_here;CID=your_cid_here;SEID=your_seid_here;KID=your_kid_here"

# 使用 alist 直链时，需要配置以下参数
alist:
  url: "http://127.0.0.1:5244"
  api_key: "your_alist_api_key_here"
  sign: true # Alist 是否使用签名

log:
  level: "info" # debug, info, warn, error
  format: "text" # json, text
  output: "file" # stdout, file
  file_path: "logs/app.log"
  max_size: 100 # MB
  max_backups: 0 # 0 means no limit
  max_age: 7 # days
  compress: true # compress old log files
