server:
  port: "9096"
  mode: "debug" # debug, release
  # 处理新增媒体事件，如果为 false，则不处理 Emby 新增媒体事件
  # 需要配置 Emby Webhook 的 URL 为 http://<server_ip>:<port>/cinexus-api/webhook/emby
  process_new_media: false

proxy:
  url: "http://127.0.0.1:8096"
  api_key: "your_emby_api_key_here"
  admin_user_id: "your_emby_admin_user_id_here"
  cache_time: 30 # 缓存直链时间，单位：分钟
  cache_pickcode: true # 缓存 pickcode 到 sqlite 数据库，提高服务速度
  add_metadata: true # 补充元数据
  # 播放时提前获取下一集的媒体信息，提高播放速度， 需要配置 admin_user_id
  add_next_media_info: true
  # 302 方式说明
  # 1. alist: 通过路径映射替换，直接请求 alist 的直链
  # 2. ck 会降级到 115open 方案，再降级到 alist 方案
  # 3. ck+115open: 通过Cookie快速获取文件PickCode，然后请求115open的直链
  # 4. 115open: 通过 115open API 的方案
  method: "alist" # alist, ck, ck+115open, 115open
  # 路径映射，用于将 Emby 的原始路径映射到代理的实际路径
  # real 字符串替换后为真实的网盘路径（用于 ck+115open 方案）
  paths:
    - old: "/vol1/1000/CloudNAS/CloudDrive/115"
      new: "/115"
      real: ""

# 使用 ck 或 ck+115open 方案时，需要配置115 Cookie
driver115:
  cookie: "UID=your_uid_here;CID=your_cid_here;SEID=your_seid_here;KID=your_kid_here"

open115:
  client_id: "your_open115_client_id_here"

# 使用 alist 直链时，需要配置以下参数
alist:
  url: "http://127.0.0.1:5244"
  api_key: "your_alist_api_key_here"
  sign: true # Alist 是否使用签名

log:
  level: "info" # debug, info, warn, error
  format: "text" # json, text
  output: "file" # stdout, file
  file_path: "logs/app.log"
  max_size: 100 # MB
  max_backups: 0 # 0 means no limit
  max_age: 7 # days
  compress: true # compress old log files

file_watcher:
  enabled: true # 是否启用文件监控功能
  configs: # 多个监控配置，可以监控不同的目录
    - name: "download-to-115" # 监控配置名称（用于日志标识）
      source_dir: "/temp" # 监控的源目录
      target_dir: "/temp2" # 目标复制目录
      extensions: [".mp4", ".mkv", ".avi", ".m4v", ".mov", ".wmv", ".flv", ".mpg", ".mpeg", ".rm", ".rmvb", ".vob", ".ts", ".tp"] # 只监控视频文件
      recursive: true # 是否递归监控子目录
      copy_mode: "copy" # 复制模式：copy(复制), move(移动), link(硬链接)
      create_dirs: true # 是否自动创建目标目录
      process_existing_files: false # 是否在启动时处理已存在的文件
